#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Define PATH for all shells, including non-login and non-interactive ones.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zpath" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zpath"
fi

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
