#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

autoload -Uz promptinit
promptinit
prompt sorin

PROMPT='[%D{%F} %D{%T}] '${PROMPT}

#
# Aliases
#

alias ll='ls -la'
alias gl='git log'
alias gs='git status --short'
alias gb='git branch'
alias gbd='git branch -d'
alias gbD='git branch -D'
alias gf='git fetch'
alias gc="echo \"gc\" is forbidden! Use \"gsw\" or \"gR\" instead. 1>&2"
alias gcb="echo \"gcb\" is forbidden! Use \"gswc\" instead. 1>&2"
alias gcm="echo \"gcm\" is forbidden! Use \"gswm\" instead. 1>&2"
alias gcmst="echo \"gcmst\" is forbidden! Use \"gswmst\" instead. 1>&2"
alias gsw="git switch"
alias gswc="git switch -c"
alias gswm="git switch main"
alias gswmst="git switch master"
alias gS='git stash'
alias gSl='git stash list'
alias gSp='git stash pop'
alias gSd='git stash drop'
alias gm='git merge'
alias ga='git add'
alias gC='git commit'
alias gCm='git commit -m'
alias gCa='git commit --amend'
alias gr='git reset'
alias grh='git reset --hard'
alias grH='git reset HEAD\^'
alias grhH='git reset --hard HEAD\^'
alias gR='git restore'
alias gp='git pull'
alias gpo='git pull origin'
alias gpom='git pull origin main'
alias gpomst='git pull origin master'
alias gP='git push'
alias gPo='git push origin'
alias gPoh='git push origin HEAD'
alias gwl='git worktree list'

gwR() { git worktree remove -f "$(git worktree list | awk -v branch="$1" '$3 == "[" branch "]" { print $1 }')"; }

#
# Key bindings
#

bindkey -e

if (( $+commands[pyenv] )); then
  eval "$(pyenv init - zsh)"
fi

if (( $+commands[direnv] )); then
  eval "$(direnv hook zsh)"
fi

# nvm completion
[ -s "${HOME}/.nvm/bash_completion" ] && \. "${HOME}/.nvm/bash_completion"  # This loads nvm bash_completion

# OpenClaw Completion
[ -f "${HOME}/.openclaw/completions/openclaw.zsh" ] && source "${HOME}/.openclaw/completions/openclaw.zsh"

# The next line enables shell command completion for gcloud.
if [ -f "${HOME}/google-cloud-sdk/completion.zsh.inc" ]; then . "${HOME}/google-cloud-sdk/completion.zsh.inc"; fi
