#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

autoload -Uz promptinit
promptinit
prompt sorin

PROMPT='[%D{%F} %D{%T}] '${PROMPT}

#
# Aliases
#

alias ll='ls -la'
alias gl='git log'
alias gs='git status --short'
alias gb='git branch'
alias gbd='gb -d'
alias gbD='gb -D'
alias gf='git fetch'
alias gc="echo \"gc\" is forbidden! Use \"gsw\" or \"gR\" instead. 1>&2"
alias gcb="echo \"gcb\" is forbidden! Use \"gswc\" instead. 1>&2"
alias gcm="echo \"gcm\" is forbidden! Use \"gswm\" instead. 1>&2"
alias gcmst="echo \"gcmst\" is forbidden! Use \"gswmst\" instead. 1>&2"
alias gsw="git switch"
alias gswc="git switch -c"
alias gswm="git switch main"
alias gswmst="git switch master"
alias gS='git stash'
alias gSl='gS list'
alias gSp='gS pop'
alias gSd='gS drop'
alias gm='git merge'
alias ga='git add'
alias gC='git commit'
alias gCm='gC -m'
alias gCa='gC --amend'
alias gr='git reset'
alias grh='gr --hard'
alias grH='git reset HEAD^'
alias grhH='gr --hard HEAD^'
alias gR='git restore'
alias gp='git pull'
alias gpo='gp origin'
alias gpom='gpo main'
alias gpomst='gpo master'
alias gP='git push'
alias gPo='gP origin'
alias gPoh='gPo HEAD'

#
# Key bindings
#

bindkey -e

#
# Interactive tools
#

[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && . "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && . "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

autoload -U add-zsh-hook
load-nvmrc() {
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$(nvm version)" ]; then
      nvm use
    fi
  elif [ -n "$(PWD=$OLDPWD nvm_find_nvmrc)" ] && [ "$(nvm version)" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc

# The next line enables shell command completion for gcloud.
if [ -f "${HOME}/google-cloud-sdk/completion.zsh.inc" ]; then . "${HOME}/google-cloud-sdk/completion.zsh.inc"; fi

if (( $+commands[pyenv] )); then
  eval "$(pyenv init - zsh)"
fi

if (( $+commands[direnv] )); then
  eval "$(direnv hook zsh)"
fi
